before_cache:
- find \$HOME/.sbt -name "*.lock" | xargs rm
- find \$HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
  - \$HOME/.ivy2/cache
  - \$HOME/.sbt

git:
  depth: 3

jdk:
- oraclejdk8

language: scala

script: sbt test

sudo: false

language: scala
